name: Argos + Storybook and Storycap
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run ci:build-storybook

      - name: Screenshot Storybook with Storycap
        run: npm run ci:storycap

      - name: Upload screenshots to Argos
        run: npx -- argos upload ./screenshots
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
